name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  build-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Calculate semantic version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1

      - name: Display calculated version
        run: echo "Version: v${{ steps.calculate-version.outputs.version-string }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: List Docker context files
        run: ls -lha

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            --label "org.opencontainers.image.source=${{ github.repositoryUrl }}" \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/container-technologies:v${{ steps.calculate-version.outputs.version-string }} \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/container-technologies:latest \
            .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/container-technologies:v${{ steps.calculate-version.outputs.version-string }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/container-technologies:v${{ steps.calculate-version.outputs.version-string }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/container-technologies:latest

      - name: Create Pull Request from develop to main
        if: github.ref == 'refs/heads/develop'
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: develop
          target_branch: main
          title: Automatic Pull Request
          body: "Automatic PR from develop to main."
          labels: |
            - enhancement
            - auto-pr
          draft: false
          allow_no_diff: false
